<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Code Manager — Save, organize, and share code</title><link rel="icon" href="{{ asset('images/logo.jpg') }}"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><link rel="stylesheet" href="{{ asset('css/legacy.css') }}"><link rel="stylesheet" href="{{ asset('css/community.css') }}"></head>
<body class="landing-page"><nav class="landing-nav"><a href="{{ route('landing') }}" class="brand-title"><i class="fa-solid fa-code"></i> Code Manager</a><div>@auth<a href="{{ route('dashboard') }}" class="add-code-btn">Open Dashboard</a>@else<a href="{{ route('login') }}" class="landing-login">Login</a><a href="{{ route('register') }}" class="add-code-btn">Get Started</a>@endauth</div></nav>
<main><section class="landing-hero"><div><span class="landing-kicker"><i class="fa-solid fa-bolt"></i> YOUR PERSONAL CODE VAULT</span><h1>Save code once.<br><em>Find it forever.</em></h1><p>Organize reusable snippets in a secure personal library, then share your best solutions with developers in the community.</p><div class="landing-actions">@auth<a href="{{ route('dashboard') }}" class="add-code-btn">Go to Dashboard <i class="fa-solid fa-arrow-right"></i></a>@else<a href="{{ route('register') }}" class="add-code-btn">Create Free Account <i class="fa-solid fa-arrow-right"></i></a><a href="{{ route('login') }}" class="category-btn">Sign In</a>@endauth</div><div class="landing-trust"><strong>{{ number_format($memberCount) }}</strong> registered {{ Str::plural('member', $memberCount) }} · Private by default · Share when you choose</div></div><div class="landing-code"><div class="window-dots"><i></i><i></i><i></i></div><pre><span>function</span> saveIdea(code) {
  vault.store(code);
  <em>return</em> "ready when needed";
}</pre></div></section>
<section class="landing-community"><div class="header-title"><span class="landing-kicker">FROM THE COMMUNITY</span><h1>Recently shared snippets</h1><p>Explore useful code shared by Code Manager members.</p></div>@if($sharedSnippets->isEmpty())<div class="empty-state"><h3>The community vault is ready.</h3><p>Create an account and share the first public snippet.</p></div>@else<div class="shared-grid">@foreach($sharedSnippets as $snippet)<x-shared-snippet :snippet="$snippet" />@endforeach</div>@endif</section></main>
<footer>
WebApplication by &copy;<span class="highlight-author"> Winnce Tubtub</span> 2026 · Code Maintained by <span class="highlight-php">hndrx</span></footer><script>document.querySelectorAll('.copy-shared').forEach(button=>button.onclick=()=>navigator.clipboard.writeText(atob(button.dataset.code)))</script></body></html>
