@extends('layouts.app') @section('title','Code Vault - Code Manager') @section('page-class','codes-page')
@section('content')
<div class="header-section"><div class="header-title"><h1>Code Snippets Vault ⚡</h1><p>Organize, save, and reuse your reference codes effortlessly.</p></div><button class="add-code-btn" onclick="openModal('addModal')"><i class="fa-solid fa-plus"></i> Add New Snippet</button></div>
<div class="category-container"><a class="category-btn {{ !request('category') ? 'active' : '' }}" href="{{ route('snippets.index') }}"><i class="fa-solid fa-layer-group"></i> All Snippets</a>@foreach(['web'=>'HTML/CSS/JS','java'=>'Java','php'=>'PHP','python'=>'Python','sql'=>'Database / SQL','text'=>'Other'] as $key=>$label)<a class="category-btn {{ request('category') === $key ? 'active' : '' }}" href="{{ route('snippets.index',['category'=>$key]) }}">{{ $label }}</a>@endforeach</div>
<div class="codes-grid">@forelse($snippets as $snippet)<div class="code-card"><div class="code-card-header"><div><span class="language-badge">{{ strtoupper($snippet->language) }}</span><h3>{{ $snippet->title }}</h3></div><i class="fa-solid fa-code code-icon"></i></div><p>{{ $snippet->description ?: 'No description provided.' }}</p><div class="code-preview"><pre><code>{{ Str::limit($snippet->code,180) }}</code></pre></div><div class="card-actions"><button class="btn-action" onclick="viewSnippet({{ $snippet->id }})"><i class="fa-solid fa-eye"></i> View</button><button class="btn-action" onclick="editSnippet({{ $snippet->id }})"><i class="fa-solid fa-pen"></i> Edit</button><form method="POST" action="{{ route('snippets.destroy',$snippet) }}" onsubmit="return confirm('Delete this snippet?')">@csrf @method('DELETE')<button class="btn-action delete"><i class="fa-solid fa-trash"></i></button></form></div></div>@empty<div class="empty-state"><i class="fa-solid fa-code-merge"></i><h3>No Code Snippets Saved Yet</h3><p>Click on the <strong>"Add New Snippet"</strong> button above to save your first code.</p></div>@endforelse</div>{{ $snippets->links() }}
<div class="modal" id="addModal"><div class="modal-content"><div class="modal-header"><h3><i class="fa-solid fa-plus-circle"></i> Add New Code Snippet</h3><button class="close-btn" onclick="closeModal('addModal')">&times;</button></div><form method="POST" action="{{ route('snippets.store') }}">@csrf @include('snippets.form')<button class="add-code-btn full">Save Snippet</button></form></div></div>
<div class="modal" id="editModal"><div class="modal-content"><div class="modal-header"><h3><i class="fa-solid fa-pen"></i> Edit Code Snippet</h3><button class="close-btn" onclick="closeModal('editModal')">&times;</button></div><form id="editForm" method="POST">@csrf @method('PUT') @include('snippets.form',['prefix'=>'edit-'])<button class="add-code-btn full">Update Snippet</button></form></div></div>
<div class="modal" id="viewModal"><div class="modal-content"><div class="modal-header"><h3 id="viewTitle"><i class="fa-solid fa-code"></i> Code Snippet</h3><button class="close-btn" onclick="closeModal('viewModal')">&times;</button></div><p id="viewDesc"></p><div class="view-code-body"><pre><code id="viewCodeText"></code></pre></div><div class="modal-footer"><button class="btn-action" onclick="navigator.clipboard.writeText(document.getElementById('viewCodeText').textContent)"><i class="fa-regular fa-copy"></i> Copy Code</button></div></div></div>
@endsection
@push('scripts')<script>const snippets=@json($snippets->keyBy('id'));function openModal(id){document.getElementById(id).classList.add('active')}function closeModal(id){document.getElementById(id).classList.remove('active')}function editSnippet(id){const s=snippets[id];for(const k of ['title','language','description','code'])document.getElementById('edit-'+k).value=s[k]||'';document.getElementById('edit-public').checked=Boolean(s.is_public);const snippetsPath=window.location.pathname.replace(/\/$/,'');document.getElementById('editForm').action=snippetsPath+'/'+id;openModal('editModal')}function viewSnippet(id){const s=snippets[id];document.getElementById('viewTitle').textContent=s.title;document.getElementById('viewDesc').textContent=s.description||'';document.getElementById('viewCodeText').textContent=s.code;openModal('viewModal')}window.onclick=e=>{if(e.target.classList.contains('modal'))e.target.classList.remove('active')}</script>@endpush
